/*
  Warnings:

  - The values [EMPLOYEE] on the enum `UserRole` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "UserRole_new" AS ENUM ('ADMIN', 'ALMOXARIFE_A', 'ANALISTA_ADMINISTRATIVO_II', 'ANALISTA_AMBIENTAL_JUNIOR', 'ANALISTA_COMPRAS_JUNIOR_A', 'ANALISTA_CONTROLADORIA_JUNIOR_A', 'ANALISTA_ORCAMENTO_JUNIOR_A', 'ANALISTA_PLANEJAMENTO_JUNIOR_A', 'ASSISTENTE_ADM_V', 'ASSISTENTE_COMPRAS', 'ASSISTENTE_CONTROLADORIA_C', 'ASSISTENTE_DP_C', 'ASSISTENTE_OBRA_A', 'ASSISTENTE_TI_A', 'ASSISTENTE_FINANCEIRO', 'ASSISTENTE_TECNICO_III', 'AUX_ADMINISTRATIVO_I', 'AUX_BOMBEIRO_HIDRAULICO', 'AUXILIAR_ADMINISTRATIVO_B', 'AUXILIAR_ALMOXARIFADO', 'AUXILIAR_BOMBEIRO', 'AUXILIAR_MUNK', 'AUXILIAR_OBRA_A', 'BOMBEIRO_HIDRAULICO', 'COORDENADOR_ADM_FINANCEIRO', 'ENCARREGADO_OBRAS', 'ENCARREGADO_OBRAS_I', 'ENGENHEIRO_CIVIL', 'ESTAGIARIO', 'ESTAGIARIO_ENDOMARKETING', 'ESTAGIARIO_PROCESSOS', 'GERENTE_OBRAS', 'JOVEM_APRENDIZ', 'LIDER_EQUIPE', 'MESTRE_OBRAS', 'MOTORISTA', 'MOTORISTA_I', 'MOTORISTA_GUINCHO', 'OPERADOR_MAQUINA_TERRAPLANAGEM', 'PEDREIRO', 'RECEPCIONISTA', 'SERVENTE', 'SERVICOS_GERAIS_I', 'SERVICOS_GERAIS_II', 'SUPERVISOR_ADM_II', 'SUPERVISOR_COMPRAS', 'SUPERVISOR_DP_A', 'SUPERVISOR_DH', 'SUPERVISOR_OBRA', 'SUPERVISOR_SEGURANCA_TRABALHO', 'SUPERVISOR_FINANCEIRO', 'TECNICO_SEGURANCA_TRABALHO_II', 'TOPOGRAFO', 'VIGIA');
ALTER TABLE "User" ALTER COLUMN "role" DROP DEFAULT;
ALTER TABLE "User" ALTER COLUMN "role" TYPE "UserRole_new" USING ("role"::text::"UserRole_new");
ALTER TYPE "UserRole" RENAME TO "UserRole_old";
ALTER TYPE "UserRole_new" RENAME TO "UserRole";
DROP TYPE "UserRole_old";
COMMIT;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "role" DROP DEFAULT;
